### ISSUE TITLE
【重要】Twitterからぶった切られる

### ISSUE THREAD

**Issue by korei-xlix** [korei-xlix/koreibot_win#6]
Twitter APIについてはソフトで制限管理しているが、それを破るくらいbotの実行が多いとTwitterからソケットを切られることがある。なお、これはRate Limitのような動きだけど、15分で制限値が解除されても再びソケット切断されるので、それ以外の閾値で切られている可能性がある。

とりわけ、Create Favo時（いいね時）に、Tweet Lookupをしている箇所があるが、このAPIはいいねの都度呼び出されるも閾値は240/15分と少ないため、これきっかけでTwitterから制限を受けている可能性が高い。

よって、いいね管理全体をもう少し負荷の低い作りに変える必要がある。

いちおログ。

******************************
いいね情報取得
******************************
処理中です。しばらくお待ちください......

○解除対象外: 2022-09-25 22:26:37 : mizo_ne
○解除対象外: 2022-09-25 22:32:17 : SatriaCtr
○解除対象外: 2022-09-25 22:32:27 : nihoninstructor
○解除対象外: 2022-09-25 22:33:18 : ReNa282021
○解除対象外: 2022-09-25 22:33:57 : 5sicmc05FOyUcnX
○解除対象外: 2022-09-25 22:36:45 : inugamikorone
○解除対象外: 2022-09-25 22:38:29 : KineticGame
○解除対象外: 2022-09-25 22:44:07 : kotonegami
いいね解除対象数= 298 個

T : いいね解除: id=1574018127343525888: 2022-09-25 21:49:00 : HaleyCarrots
T : いいね解除: id=1574018423943839753: 2022-09-25 21:50:10 : OutFarsi
T : いいね解除: id=1574020979147173888: 2022-09-25 22:00:19 : oozorasubaru
T : いいね解除: id=1574021200887836673: 2022-09-25 22:01:12 : yunetyandayo
T : いいね解除: id=1574021420098752513: 2022-09-25 22:02:05 : kdpifarsi
Traceback (most recent call last):
  File "Z:\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "Z:\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "Z:\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "Z:\Python\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "Z:\Python\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "Z:\Python\Python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "Z:\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "Z:\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "Z:\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] 既存の接続はリモート ホストに強制的に切断されました。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "Z:\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "Z:\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "Z:\Python\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "Z:\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "Z:\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "Z:\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "Z:\Python\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "Z:\Python\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "Z:\Python\Python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "Z:\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "Z:\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "Z:\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '既存の接続はリモート ホストに強制的に切断されました。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 22, in <module>
    CLS_Main_Console.sRun()             #コンソール起動
  File "script\main_console.py", line 129, in sRun
    wResCmd = cls().sRunCommand( wCommand )
  File "script\main_console.py", line 178, in sRunCommand
    cls.OBJ_TwitterMain.AllRun()
  File "script/func\twitter_main.py", line 836, in AllRun
    wSubRes = self.OBJ_TwitterFavo.RemFavo()
  File "script/func\twitter_favo.py", line 157, in RemFavo
    wRemoveRes = gVal.OBJ_Tw_IF.FavoRemove( wID )
  File "script/data\twitter_if.py", line 1560, in FavoRemove
    wTwitterRes = self.OBJ_Twitter.RemoveFavo( inID )
  File "script/api\twitter_use.py", line 2640, in RemoveFavo
    wTweetRes = self.Twitter_use.post( wAPI, params=wParams )
  File "Z:\Python\Python38\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "Z:\Python\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "Z:\Python\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "Z:\Python\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '既存の接続はリモート  ホストに強制的に切断されました。', None, 10054, None))

D:\Source\koreibot_win>cd ..

D:\Source>rem echo koreibot.bat

**Comment by korei-xlix** [comment]
本件2.5.1で修正済み。
